export enum AstNodeType {
  // general
  Token = "Token",
  TokenSequence = "TokenSequence",
  Text = "Text",
  Operator = "Operator",
  Module = "Module",
  Program = "Program",
  Keyword = "Keyword",
  DebuggerKeyword = "DebuggerKeyword",
  CommentLine = "CommentLine",
  CommentBlock = "CommentBlock",
  // literals
  Number = "Number",
  String = "String",
  Boolean = "Boolean",
  Array = "Array",
  // identifiers
  Identifier = "Identifier",
  IdentifierScope = "IdentifierScope",
  RawIdentifier = "RawIdentifier",
  ContextIdentifier = "ContextIdentifier",
  // declarations
  FunctionDeclaration = "FunctionDeclaration",
  VariableDeclaration = "VariableDeclaration",
  PropertyDeclaration = "PropertyDeclaration",
  // statements
  Statement = "Statement",
  BreakStatement = "BreakStatement",
  ReturnStatement = "ReturnStatement",
  ContinueStatement = "ContinueStatement",
  BlockStatement = "BlockStatement",
  IfStatement = "IfStatement",
  SwitchStatement = "SwitchStatement",
  CaseStatement = "CaseStatement",
  WhileStatement = "WhileStatement",
  DoWhileStatement = "DoWhileStatement",
  ForStatement = "ForStatement",
  ForInStatement = "ForInStatement",
  ImportStatement = "ImportStatement",
  TryStatement = "TryStatement",
  CatchStatement = "CatchStatement",
  FinallyStatement = "FinallyStatement",
  ThrowStatement = "ThrowStatement",
  // expression statements
  ExpressionStatement = "ExpressionStatement",
  ParenExpression = "ParenExpression",
  ObjectExpression = "ObjectExpression",
  CallExpression = "CallExpression",
  OperationExpression = "OperationExpression",
  UpdateExpression = "UpdateExpression",
  BinaryExpression = "BinaryExpression",
  MemberExpression = "MemberExpression",
  IndexerExpression = "IndexerExpression",
  ConditionalExpression = "ConditionalExpression",
  NewExpression = "NewExpression",
  DeleteExpression = "DeleteExpression",
  TypeofExpression = "TypeofExpression",
  // storytailor-specific
  OuterStatement = "OuterStatement",
  TextLineStatement = "TextLineStatement",
  ObjectLineStatement = "ObjectLineStatement",
  StringIncludeStatement = "StringIncludeStatement",
  PrototypeExpression = "PrototypeExpression",
  DeleteLineExpression = "DeleteLineExpression",
  Scope = "Scope",
  Tag = "Tag",
}
