export enum OperatorType {
  Equals = "Equals",
  DoubleEquals = "DoubleEquals",
  TripleEquals = "TripleEquals",
  NotEqualsEquals = "NotEqualsEquals",
  NotEquals = "NotEquals",
  Plus = "Plus",
  PlusPlus = "PlusPlus",
  Minus = "Minus",
  Not = "Not",
  MinusMinus = "MinusMinus",
  Multiply = "Multiply",
  Divide = "Divide",
  Greater = "Greater",
  Less = "Less",
  GreaterOrEquals = "GreaterOrEquals",
  LessOrEquals = "LessOrEquals",
  SpreadAssign = "SpreadAssign",
  OrOr = "OrOr",
  AndAnd = "AndAnd",
  SingleOr = "SingleOr",
  SingleAnd = "SingleAnd"
}
